### ISSUE TITLE
Query regarding contribution.

### ISSUE THREAD

**Issue by ProPhycient5** [zero-to-mastery/coding_challenge-44#8]
In this current challenge, can I contribute using reactJS ?
As I am learning ReactJS, so it would be better for me to become more handy, if you guys permit, then I will create one SPA using reactJS.
Please do respond.

**Comment by aymanxdev** [comment]
I think it would be better to keep it simple HTML. CSS and JS. I found another React coding challenge that might be helpful 
Check it out here [React Coding Challenges](https://github.com/zero-to-mastery/coding_challenge-19)

**Comment by SL972** [comment]
I think you can only use HTML, CSS JS, no, other libraries or some sort of stuff.

**Comment by ProPhycient5** [comment]
Thank you @SL972 for your response.
